import type { RunDestination, RunOptions } from "../../shared/schemas.js";
import {
  verificationReceiptHash,
  verifyCommitFileDigests,
  verifyFileDigests,
} from "../workspace/verificationReceipt.js";
import {
  branchUrlFor,
  commitRunFiles,
  compareUrlFor,
  githubCreateRepo,
  initRepo,
  originUrl,
  pushBranch,
  releaseToMain,
  currentBranch,
  failureText,
  git,
} from "../workspace/gitOps.js";
import { detectHostCi } from "../workspace/hostCi.js";
import { planTrunkAdvance } from "./releasePlan.js";

/**
 * deliverRun.ts — SAVE THE WORK WHERE THE OWNER SAID TO SAVE IT.
 *
 * Owner order, 2026-08-13:
 *   "whichever git repo I add prior to the prompt is the one that the work
 *    should be saved in"
 *   "If it is a new app altogether, it should ask me what to name the app/repo,
 *    then create it"
 *
 * Before this existed, EVERY run — extend or new — ended with its output
 * stranded in `workspaces/<slug>-<runid>`: extend runs cloned the attached repo
 * with its `origin` deliberately removed, and new apps got a slug derived from
 * whatever the model decided to call the app. The finished work never reached a
 * repo the owner would ever open again.
 *
 * Owner order, 2026-08-19:
 *   "The work is pushed to main directly so it is in production."
 * Owner decision, 2026-08-20:
 *   "protect factory deck's trunk."
 *
 * A branch pushed and left sitting there is not delivered work — it is work
 * waiting for a human to remember it. But advancing the trunk on Factory Deck's
 * own say-so is not the answer either. So an extend run ends with its work
 * PUBLISHED and ON ITS WAY to the trunk through the HOST repo's own gate: the
 * run's `factory-deck/<id>` branch carries the commit (it is the audit trail,
 * and it is where a conflict fails safely), and the trunk advances only through
 * a pull request the host's CI passed, with auto-merge armed so no human is
 * needed. `planTrunkAdvance` (releasePlan.ts) makes that call; the direct
 * fast-forward remains only as its NAMED fallback.
 *
 * Delivery runs ONCE, at the end of a run that actually completed:
 *   - existing-repo → commit the run's own files onto `factory-deck/<id>` and
 *     push it. The trunk is then either left to the PR gate (the default) or,
 *     on the named fallback, fast-forwarded onto the branch (never --force; a
 *     rejected fast-forward is reported, not overridden);
 *   - new-repo      → git init, commit, `gh repo create owner/name --private
 *     --source . --push`;
 *   - workspace-only→ nothing to deliver; say so plainly.
 *
 * Failure is REPORTED, never swallowed and never fatal: a completed build whose
 * push was rejected must still show as completed with a destination that says
 * exactly what went wrong, so the owner can fix credentials and push by hand.
 */

export interface DeliveryInput {
  destination: RunDestination;
  workspacePath: string;
  /** Workspace-relative paths this run generated or modified. */
  filePaths: string[];
  /** Used for the commit message. */
  runId: string;
  appName: string | null;
  options: RunOptions;
  /** Required evidence for every real delivery; absence fails closed. */
  verification: {
    qaPassed: boolean;
    testStatus: "passing" | "failing" | "skipped" | "unknown";
    writeRefusals: number;
    incompleteCommands: number;
    fileDigests?: Record<string, string>;
  };
}

function commitMessage(input: DeliveryInput): string {
  const name = input.appName?.trim() || "Factory Deck run";
  return `${name}: Factory Deck run ${input.runId.slice(0, 8)}

Generated by Factory Deck's agent assembly line.
Files in this commit: ${input.filePaths.length}.

Factory-Deck-Run: ${input.runId}
Factory-Deck-Receipt: ${verificationReceiptHash(input.verification.fileDigests)}`;
}

/**
 * Plan where a run's output will be saved. Called BEFORE building so the UI can
 * show the destination up front rather than revealing it after the fact.
 */
export function planDestination(args: {
  mode: "new" | "extend";
  options: RunOptions;
  /** For extend runs: the repo the ingested workspace can push back to. */
  originUrl?: string | null;
  branch?: string | null;
  /** Resolved GitHub owner for a new repo. */
  githubOwner?: string | null;
}): RunDestination {
  if (args.mode === "new") {
    const nr = args.options.newRepo;
    if (!nr) {
      return {
        kind: "workspace-only",
        target: "(no repo attached)",
        branch: null,
        status: "planned",
        detail:
          "No app/repo name was given, so the work stays in its workspace folder.",
        url: null,
        deliveredAt: null,
      };
    }
    const owner = nr.owner?.trim() || args.githubOwner?.trim() || "";
    const createRemote = nr.createRemote !== false;
    const full = owner ? `${owner}/${nr.name}` : nr.name;
    return {
      kind: "new-repo",
      target: full,
      branch: "main",
      status: "planned",
      detail: createRemote
        ? `A new ${nr.private === false ? "public" : "private"} GitHub repo will be created and the work pushed to it.`
        : "A local git repo will be created in the workspace (no GitHub repo requested).",
      url: createRemote && owner ? `https://github.com/${full}` : null,
      deliveredAt: null,
    };
  }

  if (!args.originUrl) {
    return {
      kind: "workspace-only",
      target: "(attached source has no git remote)",
      branch: args.branch ?? null,
      status: "planned",
      detail:
        "The attached source is not a git repo, so there is nowhere to push the branch back to. The work stays in its workspace folder.",
      url: null,
      deliveredAt: null,
    };
  }

  return {
    kind: "existing-repo",
    target: args.originUrl,
    branch: args.branch ?? null,
    status: "planned",
    detail:
      `The run's changes will be committed on ${args.branch ?? "its own branch"}, ` +
      "pushed back to this repo, and opened as a pull request against its default " +
      "branch — the repo's own CI checks gate the merge, with auto-merge armed so " +
      "a green PR lands without a human.",
    url: null,
    deliveredAt: null,
  };
}

/** Perform the delivery. Never throws — the outcome is the return value. */
export async function deliverRun(input: DeliveryInput): Promise<RunDestination> {
  const dest = { ...input.destination };
  const now = Date.now();

  // A simulated run NEVER writes into a real repository. The mock/stub
  // providers emit canned, unrelated source (a Bible-streak React demo); a
  // measured run proved that landing in an attached repo it overwrote the
  // owner's own package.json and README on a `factory-deck/<id>` branch, and
  // reported status "delivered". Release-to-main and deploy were already
  // demo-gated; delivery was not. Fail LOUD and skip — never silently, and
  // never as a success.
  if (input.options.demo === true) {
    return {
      ...dest,
      status: "skipped",
      detail:
        "REFUSED: this run used the offline mock provider, so its output is " +
        "simulated and was NOT written to the target repo. Re-run against a " +
        "real provider (free route or a paid key) to deliver real work.",
      deliveredAt: now,
    };
  }

  const verification = input.verification;
  if (
    !verification ||
    !verification.qaPassed ||
    verification.testStatus !== "passing" ||
    verification.writeRefusals > 0 ||
    verification.incompleteCommands > 0
  ) {
    return {
      ...dest,
      status: "skipped",
      detail:
        "REFUSED: verification gate did not pass, so no commit, branch push, PR, " +
        "or release was attempted.",
      deliveredAt: now,
    };
  }

  const receipt = await verifyFileDigests(
    input.workspacePath,
    input.filePaths,
    verification.fileDigests,
  );
  if (!receipt.ok) {
    return {
      ...dest,
      status: "skipped",
      detail:
        `REFUSED: verified file receipt is invalid (${receipt.reason ?? "unknown reason"}); ` +
        "no commit, push, PR, or release was attempted.",
      deliveredAt: now,
    };
  }

  const receiptStillValid = async (): Promise<RunDestination | null> => {
    const check = await verifyFileDigests(
      input.workspacePath,
      input.filePaths,
      verification.fileDigests,
    );
    return check.ok
      ? null
      : {
          ...dest,
          status: "failed",
          detail:
            `REFUSED: deliverable bytes changed during commit preparation (${check.reason ?? "unknown reason"}); ` +
            "nothing was pushed.",
          deliveredAt: Date.now(),
        };
  };

  const resolveVerifiedCommit = async (commit: {
    committed: boolean;
    unchanged: boolean;
    detail: string;
    sha: string | null;
  }): Promise<{ sha: string | null; detail: string; reason?: string }> => {
    let sha = commit.sha;
    let detail = commit.detail;
    if (!commit.committed) {
      if (!commit.unchanged) return { sha: null, detail, reason: detail };
      const head = await git(["rev-parse", "HEAD"], input.workspacePath, 15_000);
      const message = await git(
        ["log", "-1", "--format=%B", "HEAD"],
        input.workspacePath,
        15_000,
      );
      const receiptHash = verificationReceiptHash(verification.fileDigests);
      const expectedRun = `Factory-Deck-Run: ${input.runId}`;
      const expectedReceipt = `Factory-Deck-Receipt: ${receiptHash}`;
      if (
        head.code !== 0 ||
        !head.stdout.trim() ||
        message.code !== 0 ||
        !message.stdout.includes(expectedRun) ||
        !message.stdout.includes(expectedReceipt)
      ) {
        return {
          sha: null,
          detail,
          reason:
            "nothing new was staged, and HEAD is not a receipt-bound commit for this run",
        };
      }
      sha = head.stdout.trim();
      detail = `Reusing receipt-bound commit ${sha.slice(0, 12)} after an interrupted delivery.`;
    }
    if (!sha) {
      return {
        sha: null,
        detail,
        reason: "commit succeeded but its SHA could not be verified",
      };
    }
    const tree = verifyCommitFileDigests(
      input.workspacePath,
      sha,
      input.filePaths,
      verification.fileDigests,
    );
    return tree.ok
      ? { sha, detail }
      : {
          sha: null,
          detail,
          reason: tree.reason ?? "committed tree receipt is invalid",
        };
  };

  try {
    if (dest.kind === "workspace-only") {
      return {
        ...dest,
        status: "skipped",
        detail:
          dest.detail ??
          "No repo attached — the finished work is in the workspace folder.",
        deliveredAt: now,
      };
    }

    if (dest.kind === "new-repo") {
      const init = await initRepo(input.workspacePath);
      if (init && init.code !== 0) {
        return {
          ...dest,
          status: "failed",
          detail: `git init failed — ${failureText(init)}`,
          deliveredAt: now,
        };
      }
      const commit = await commitRunFiles(
        input.workspacePath,
        input.filePaths,
        commitMessage(input),
      );
      const verifiedCommit = await resolveVerifiedCommit(commit);
      if (!verifiedCommit.sha) {
        return {
          ...dest,
          status: "failed",
          detail:
            `REFUSED: ${verifiedCommit.reason ?? "committed tree is not verified"}; ` +
            "nothing was pushed.",
          deliveredAt: now,
        };
      }
      const changedDuringNewCommit = await receiptStillValid();
      if (changedDuringNewCommit) return changedDuringNewCommit;
      if (input.options.newRepo?.createRemote === false) {
        return {
          ...dest,
          status: "delivered",
          detail: `${verifiedCommit.detail} Local git repo only (no GitHub repo requested): ${input.workspacePath}`,
          commitSha: verifiedCommit.sha,
          deliveredAt: now,
        };
      }
      // Already wired to a remote (a re-delivery): push instead of re-creating.
      const existingRemote = await originUrl(input.workspacePath);
      if (existingRemote) {
        const branch = (await currentBranch(input.workspacePath)) ?? "main";
        const res = await git(
          ["push", "-u", "origin", `${branch}:${branch}`],
          input.workspacePath,
          600_000,
        );
        return {
          ...dest,
          status: res.code === 0 ? "delivered" : "failed",
          detail:
            res.code === 0
              ? `${verifiedCommit.detail} Pushed ${branch} to ${existingRemote}.`
              : `${verifiedCommit.detail} git push failed — ${failureText(res)}`,
          commitSha: verifiedCommit.sha,
          deliveredAt: now,
        };
      }
      const created = await githubCreateRepo({
        fullName: dest.target,
        dir: input.workspacePath,
        private: input.options.newRepo?.private !== false,
      });
      return {
        ...dest,
        status: created.created ? "delivered" : "failed",
        detail: `${verifiedCommit.detail} ${created.detail}`,
        url: created.url ?? dest.url,
        commitSha: verifiedCommit.sha,
        deliveredAt: now,
      };
    }

    // existing-repo
    if (input.options.pushToOrigin === false) {
      return {
        ...dest,
        status: "skipped",
        detail: "Push back to origin was explicitly disabled for this run.",
        deliveredAt: now,
      };
    }
    const branch = dest.branch ?? (await currentBranch(input.workspacePath)) ?? null;
    if (!branch) {
      return {
        ...dest,
        status: "failed",
        detail: "Could not determine which branch to deliver (detached HEAD).",
        deliveredAt: now,
      };
    }
    const commit = await commitRunFiles(
      input.workspacePath,
      input.filePaths,
      commitMessage(input),
    );
    const verifiedCommit = await resolveVerifiedCommit(commit);
    if (!verifiedCommit.sha) {
      return {
        ...dest,
        branch,
        status: "failed",
        detail:
          `REFUSED: ${verifiedCommit.reason ?? "committed tree is not verified"}; ` +
          "nothing was pushed.",
        deliveredAt: now,
      };
    }
    const changedDuringCommit = await receiptStillValid();
    if (changedDuringCommit) return { ...changedDuringCommit, branch };
    const pushed = await pushBranch(input.workspacePath, branch);
    const remote = (await originUrl(input.workspacePath)) ?? dest.target;
    if (!pushed.pushed) {
      return {
        ...dest,
        branch,
        status: "failed",
        detail: `${verifiedCommit.detail} ${pushed.detail}`,
        url: null,
        commitSha: verifiedCommit.sha,
        deliveredAt: now,
      };
    }

    // The branch is published. WHO IS ALLOWED TO MOVE THE TRUNK FROM HERE is a
    // single decision, made in releasePlan.ts (owner decision 2026-08-20,
    // "protect factory deck's trunk"): by default the HOST repo's CI gates it
    // through a pull request, and delivery stops at the published branch.
    const ci = detectHostCi(input.workspacePath);
    const trunkPlan = planTrunkAdvance({
      directTrunkAdvance: input.options.directTrunkAdvance,
      hostCi: ci.presence,
    });
    if (trunkPlan.path === "pr-gate") {
      // Delivered = the work reached the repo, on a published branch bound to
      // the verified commit. It is NOT on the trunk and NOT in production, and
      // the detail says exactly that — the release step that follows opens the
      // PR and lets the host repo's checks decide.
      return {
        ...dest,
        branch,
        status: "delivered",
        detail:
          `${verifiedCommit.detail} ${pushed.detail} ${trunkPlan.reason} ` +
          "The trunk was NOT advanced by this delivery.",
        url: compareUrlFor(remote, branch),
        commitSha: verifiedCommit.sha,
        branchPushed: true,
        releasedToTrunk: false,
        trunkAdvancePath: "pr-gate",
        deliveredAt: now,
      };
    }

    // NAMED FALLBACK ONLY (no host CI, or an explicit owner opt-in): put the
    // work on the trunk directly. Everything above this line is the evidence
    // that earns it — the demo gate, the verification gate, and the receipt
    // check over the committed tree. A run that did not pass those never
    // reaches here.
    const released = await releaseToMain(input.workspacePath, branch);
    if (!released.released) {
      // The branch push SUCCEEDED, so the work exists and is recoverable — but
      // it is not on the trunk, so it is NOT in production. Reporting this as
      // "delivered" would be the silent half-success this deck exists to
      // prevent. It is a failure with the recovery path spelled out.
      //
      // `branchPushed: true` is what tells the caller the difference between
      // "nothing reached the repo" and "only the trunk did not move". The
      // second is exactly what a PROTECTED trunk looks like, and the repo's
      // own PR gate is the correct recovery for it — see runFactory, which
      // routes this case to releaseRun instead of stopping here.
      return {
        ...dest,
        branch,
        status: "failed",
        detail: `${verifiedCommit.detail} ${pushed.detail} ${trunkPlan.reason} NOT RELEASED: ${released.detail}`,
        url: compareUrlFor(remote, branch),
        commitSha: verifiedCommit.sha,
        branchPushed: true,
        releasedToTrunk: false,
        trunkAdvancePath: "direct-fast-forward",
        deliveredAt: now,
      };
    }
    return {
      ...dest,
      branch,
      status: "delivered",
      detail: `${verifiedCommit.detail} ${pushed.detail} ${trunkPlan.reason} ${released.detail}`,
      url:
        (released.trunk ? branchUrlFor(remote, released.trunk) : null) ??
        compareUrlFor(remote, branch),
      commitSha: verifiedCommit.sha,
      branchPushed: true,
      // The trunk now POINTS AT this branch. Anything downstream that would
      // open a PR from it would be opening an empty one.
      releasedToTrunk: true,
      trunkAdvancePath: "direct-fast-forward",
      deliveredAt: now,
    };
  } catch (err) {
    return {
      ...dest,
      status: "failed",
      detail: `Delivery failed unexpectedly: ${
        err instanceof Error ? err.message : "unknown error"
      }`,
      deliveredAt: now,
    };
  }
}
