import type { RunDestination, RunOptions } from "../../shared/schemas.js";
import {
  commitRunFiles,
  compareUrlFor,
  githubCreateRepo,
  initRepo,
  originUrl,
  pushBranch,
  currentBranch,
  failureText,
  git,
} from "../workspace/gitOps.js";

/**
 * deliverRun.ts — SAVE THE WORK WHERE THE OWNER SAID TO SAVE IT.
 *
 * Owner order, 2026-08-13:
 *   "whichever git repo I add prior to the prompt is the one that the work
 *    should be saved in"
 *   "If it is a new app altogether, it should ask me what to name the app/repo,
 *    then create it"
 *
 * Before this existed, EVERY run — extend or new — ended with its output
 * stranded in `workspaces/<slug>-<runid>`: extend runs cloned the attached repo
 * with its `origin` deliberately removed, and new apps got a slug derived from
 * whatever the model decided to call the app. The finished work never reached a
 * repo the owner would ever open again.
 *
 * Delivery runs ONCE, at the end of a run that actually completed:
 *   - existing-repo → commit the run's own files, push `factory-deck/<id>` to
 *     origin (never main, never --force), hand back a compare/PR link;
 *   - new-repo      → git init, commit, `gh repo create owner/name --private
 *     --source . --push`;
 *   - workspace-only→ nothing to deliver; say so plainly.
 *
 * Failure is REPORTED, never swallowed and never fatal: a completed build whose
 * push was rejected must still show as completed with a destination that says
 * exactly what went wrong, so the owner can fix credentials and push by hand.
 */

export interface DeliveryInput {
  destination: RunDestination;
  workspacePath: string;
  /** Workspace-relative paths this run generated or modified. */
  filePaths: string[];
  /** Used for the commit message. */
  runId: string;
  appName: string | null;
  options: RunOptions;
  /** Required evidence for every real delivery; absence fails closed. */
  verification?: {
    qaPassed: boolean;
    testStatus: "passing" | "failing" | "skipped" | "unknown";
    writeRefusals: number;
  };
}

function commitMessage(input: DeliveryInput): string {
  const name = input.appName?.trim() || "Factory Deck run";
  return `${name}: Factory Deck run ${input.runId.slice(0, 8)}

Generated by Factory Deck's agent assembly line.
Files in this commit: ${input.filePaths.length}.`;
}

/**
 * Plan where a run's output will be saved. Called BEFORE building so the UI can
 * show the destination up front rather than revealing it after the fact.
 */
export function planDestination(args: {
  mode: "new" | "extend";
  options: RunOptions;
  /** For extend runs: the repo the ingested workspace can push back to. */
  originUrl?: string | null;
  branch?: string | null;
  /** Resolved GitHub owner for a new repo. */
  githubOwner?: string | null;
}): RunDestination {
  if (args.mode === "new") {
    const nr = args.options.newRepo;
    if (!nr) {
      return {
        kind: "workspace-only",
        target: "(no repo attached)",
        branch: null,
        status: "planned",
        detail:
          "No app/repo name was given, so the work stays in its workspace folder.",
        url: null,
        deliveredAt: null,
      };
    }
    const owner = nr.owner?.trim() || args.githubOwner?.trim() || "";
    const createRemote = nr.createRemote !== false;
    const full = owner ? `${owner}/${nr.name}` : nr.name;
    return {
      kind: "new-repo",
      target: full,
      branch: "main",
      status: "planned",
      detail: createRemote
        ? `A new ${nr.private === false ? "public" : "private"} GitHub repo will be created and the work pushed to it.`
        : "A local git repo will be created in the workspace (no GitHub repo requested).",
      url: createRemote && owner ? `https://github.com/${full}` : null,
      deliveredAt: null,
    };
  }

  if (!args.originUrl) {
    return {
      kind: "workspace-only",
      target: "(attached source has no git remote)",
      branch: args.branch ?? null,
      status: "planned",
      detail:
        "The attached source is not a git repo, so there is nowhere to push the branch back to. The work stays in its workspace folder.",
      url: null,
      deliveredAt: null,
    };
  }

  return {
    kind: "existing-repo",
    target: args.originUrl,
    branch: args.branch ?? null,
    status: "planned",
    detail: `The run's changes will be committed on ${args.branch ?? "its own branch"} and pushed back to this repo.`,
    url: null,
    deliveredAt: null,
  };
}

/** Perform the delivery. Never throws — the outcome is the return value. */
export async function deliverRun(input: DeliveryInput): Promise<RunDestination> {
  const dest = { ...input.destination };
  const now = Date.now();

  // A simulated run NEVER writes into a real repository. The mock/stub
  // providers emit canned, unrelated source (a Bible-streak React demo); a
  // measured run proved that landing in an attached repo it overwrote the
  // owner's own package.json and README on a `factory-deck/<id>` branch, and
  // reported status "delivered". Release-to-main and deploy were already
  // demo-gated; delivery was not. Fail LOUD and skip — never silently, and
  // never as a success.
  if (input.options.demo === true) {
    return {
      ...dest,
      status: "skipped",
      detail:
        "REFUSED: this run used the offline mock provider, so its output is " +
        "simulated and was NOT written to the target repo. Re-run against a " +
        "real provider (free route or a paid key) to deliver real work.",
      deliveredAt: now,
    };
  }

  const verification = input.verification;
  if (
    !verification ||
    !verification.qaPassed ||
    verification.testStatus !== "passing" ||
    verification.writeRefusals > 0
  ) {
    return {
      ...dest,
      status: "skipped",
      detail:
        "REFUSED: verification gate did not pass, so no commit, branch push, PR, " +
        "or release was attempted.",
      deliveredAt: now,
    };
  }

  try {
    if (dest.kind === "workspace-only") {
      return {
        ...dest,
        status: "skipped",
        detail:
          dest.detail ??
          "No repo attached — the finished work is in the workspace folder.",
        deliveredAt: now,
      };
    }

    if (dest.kind === "new-repo") {
      const init = await initRepo(input.workspacePath);
      if (init && init.code !== 0) {
        return {
          ...dest,
          status: "failed",
          detail: `git init failed — ${failureText(init)}`,
          deliveredAt: now,
        };
      }
      const commit = await commitRunFiles(
        input.workspacePath,
        input.filePaths,
        commitMessage(input),
      );
      if (!commit.committed) {
        return { ...dest, status: "failed", detail: commit.detail, deliveredAt: now };
      }
      if (input.options.newRepo?.createRemote === false) {
        return {
          ...dest,
          status: "delivered",
          detail: `${commit.detail} Local git repo only (no GitHub repo requested): ${input.workspacePath}`,
          deliveredAt: now,
        };
      }
      // Already wired to a remote (a re-delivery): push instead of re-creating.
      const existingRemote = await originUrl(input.workspacePath);
      if (existingRemote) {
        const branch = (await currentBranch(input.workspacePath)) ?? "main";
        const res = await git(
          ["push", "-u", "origin", `${branch}:${branch}`],
          input.workspacePath,
          600_000,
        );
        return {
          ...dest,
          status: res.code === 0 ? "delivered" : "failed",
          detail:
            res.code === 0
              ? `${commit.detail} Pushed ${branch} to ${existingRemote}.`
              : `${commit.detail} git push failed — ${failureText(res)}`,
          deliveredAt: now,
        };
      }
      const created = await githubCreateRepo({
        fullName: dest.target,
        dir: input.workspacePath,
        private: input.options.newRepo?.private !== false,
      });
      return {
        ...dest,
        status: created.created ? "delivered" : "failed",
        detail: `${commit.detail} ${created.detail}`,
        url: created.url ?? dest.url,
        deliveredAt: now,
      };
    }

    // existing-repo
    if (input.options.pushToOrigin === false) {
      return {
        ...dest,
        status: "skipped",
        detail: "Push back to origin was explicitly disabled for this run.",
        deliveredAt: now,
      };
    }
    const branch =
      dest.branch ?? (await currentBranch(input.workspacePath)) ?? null;
    if (!branch) {
      return {
        ...dest,
        status: "failed",
        detail: "Could not determine which branch to deliver (detached HEAD).",
        deliveredAt: now,
      };
    }
    const commit = await commitRunFiles(
      input.workspacePath,
      input.filePaths,
      commitMessage(input),
    );
    if (!commit.committed) {
      return {
        ...dest,
        branch,
        status: "failed",
        detail: commit.detail,
        deliveredAt: now,
      };
    }
    const pushed = await pushBranch(input.workspacePath, branch);
    const remote = (await originUrl(input.workspacePath)) ?? dest.target;
    return {
      ...dest,
      branch,
      status: pushed.pushed ? "delivered" : "failed",
      detail: `${commit.detail} ${pushed.detail}`,
      url: pushed.pushed ? compareUrlFor(remote, branch) : null,
      deliveredAt: now,
    };
  } catch (err) {
    return {
      ...dest,
      status: "failed",
      detail: `Delivery failed unexpectedly: ${
        err instanceof Error ? err.message : "unknown error"
      }`,
      deliveredAt: now,
    };
  }
}
