import { gh, failureText, type ExecResult } from "../workspace/gitOps.js";

const succeeded = (r: ExecResult): boolean => r.code === 0 && !r.spawnError;

/**
 * releaseRun.ts — FINISH THE JOB: an extend run that EARNED it merges to main.
 *
 * Owner order 2026-08-15: "When the run finishes factory deck, it should be
 * either a new program, or in this case with grantflow, a patch that improved
 * the program towards its purpose, and placed into production." Delivery used
 * to stop at pushing `factory-deck/<id>` — a branch nobody deploys. The last
 * mile is the intake's own Phase 10: open the PR, let the HOST repo's checks
 * run, merge only when they pass, and report the merged SHA.
 *
 * THE GATE IS EARNED EVIDENCE, NEVER MODEL JUDGMENT — three keys, all hard:
 *   1. the run's grounded QA passed (every executed verification command
 *      exited 0 — qaGrounding is the authority);
 *   2. tests actually EXECUTED and exited 0 (testStatus === "passing";
 *      "unknown" — nothing ran — can never release);
 *   3. the host repository's OWN CI checks go green on the PR (its branch
 *      protections and suites are the final word, exactly as they are for a
 *      human contributor).
 * A run that misses any key still delivers its branch + an OPEN PR with the
 * reason recorded — released is a claim only a merge can make, and the
 * deployed-production claim belongs to the repo's own deploy-from-main
 * automation, which the report names rather than asserts.
 *
 * Release failures NEVER fail the run: the build is delivered either way, and
 * pretending otherwise would lie in both directions.
 */

export interface ReleaseInput {
  /** e.g. https://github.com/owner/repo — the destination target. */
  repoUrl: string;
  branch: string;
  runId: string;
  appName: string | null;
  qaPassed: boolean;
  testStatus: "passing" | "failing" | "unknown";
  /** Final-report caveats (unwired scaffolding etc.) surfaced in the PR body. */
  caveats: string[];
  /** Injectable gh runner for tests. */
  ghImpl?: typeof gh;
  /** Injectable sleep for tests. */
  sleepImpl?: (ms: number) => Promise<void>;
  /** Max time to wait for the host repo's checks. */
  checkTimeoutMs?: number;
}

export interface ReleaseResult {
  released: boolean;
  prUrl: string | null;
  mergedSha: string | null;
  reason: string;
}

/** owner/repo from a github URL, or null when it is not a github remote. */
export function repoSlug(repoUrl: string): string | null {
  const m = /github\.com[/:]([^/]+)\/([^/.\s]+)/i.exec(repoUrl);
  return m ? `${m[1]}/${m[2]}` : null;
}

/** The evidence gate — pure, so tests pin it directly. */
export function releaseEligible(input: {
  qaPassed: boolean;
  testStatus: ReleaseInput["testStatus"];
}): { eligible: boolean; reason: string } {
  if (!input.qaPassed) {
    return {
      eligible: false,
      reason: "grounded QA did not pass — the branch and an open PR are the honest deliverable",
    };
  }
  if (input.testStatus !== "passing") {
    return {
      eligible: false,
      reason:
        input.testStatus === "unknown"
          ? "no test command executed — an unverified build never releases"
          : "tests failed — an unverified build never releases",
    };
  }
  return { eligible: true, reason: "grounded QA green and tests passing" };
}

const CHECK_POLL_MS = 90_000;

export async function releaseRun(input: ReleaseInput): Promise<ReleaseResult> {
  const run = input.ghImpl ?? gh;
  const sleep =
    input.sleepImpl ?? ((ms: number) => new Promise((r) => setTimeout(r, ms)));
  const slug = repoSlug(input.repoUrl);
  if (!slug) {
    return {
      released: false,
      prUrl: null,
      mergedSha: null,
      reason: `destination is not a GitHub repo (${input.repoUrl}) — nothing to merge`,
    };
  }

  const gate = releaseEligible(input);
  const title = `${input.appName ?? "Factory Deck"}: run ${input.runId.slice(0, 8)}`;
  const caveatBlock = input.caveats.length
    ? `\n\n## Caveats\n${input.caveats.map((c) => `- ${c}`).join("\n")}`
    : "";
  const body =
    `Factory Deck ${gate.eligible ? "release" : "delivery (NOT auto-released)"} for run ${input.runId}.\n\n` +
    `Verification: ${gate.reason}.${caveatBlock}\n\n` +
    `🤖 Generated by Factory Deck.`;

  // 1. Open the PR (idempotent-ish: an existing PR for the branch is reused).
  let prUrl: string | null = null;
  const create: ExecResult = await run(
    [
      "pr", "create", "-R", slug,
      "--head", input.branch, "--base", "main",
      "--title", title, "--body", body,
    ],
    process.cwd(),
    120_000,
  );
  if (succeeded(create)) {
    prUrl = create.stdout.trim().split(/\s+/).pop() ?? null;
  } else if (/already exists/i.test(create.stderr + create.stdout)) {
    const view = await run(
      ["pr", "view", input.branch, "-R", slug, "--json", "url", "--jq", ".url"],
      process.cwd(),
      60_000,
    );
    prUrl = succeeded(view) ? view.stdout.trim() : null;
  }
  if (!prUrl) {
    return {
      released: false,
      prUrl: null,
      mergedSha: null,
      reason: `could not open the PR: ${failureText(create)}`,
    };
  }

  if (!gate.eligible) {
    return { released: false, prUrl, mergedSha: null, reason: gate.reason };
  }

  // 2. Wait for the HOST repo's own checks. `gh pr checks` exits 0 when all
  //    checks pass, 8 while pending, non-zero otherwise. A repo with no checks
  //    at all reports "no checks" — treated as pass-through (the repo imposed
  //    no gate).
  const deadline = Date.now() + (input.checkTimeoutMs ?? 45 * 60_000);
  for (;;) {
    const checks = await run(
      ["pr", "checks", prUrl, "--json", "state,name"],
      process.cwd(),
      60_000,
    );
    const raw = checks.stdout + checks.stderr;
    if (/no checks reported/i.test(raw)) break;
    let states: Array<{ state: string; name: string }> = [];
    try {
      states = JSON.parse(checks.stdout);
    } catch {
      /* non-JSON output while checks initialize — poll again */
    }
    const failed = states.filter(
      (s) => /FAILURE|ERROR|CANCELLED|TIMED_OUT|ACTION_REQUIRED/i.test(s.state),
    );
    if (failed.length) {
      return {
        released: false,
        prUrl,
        mergedSha: null,
        reason: `host repo checks failed: ${failed.map((f) => f.name).slice(0, 4).join(", ")}`,
      };
    }
    const pending = states.filter((s) => /PENDING|QUEUED|IN_PROGRESS|EXPECTED/i.test(s.state));
    if (states.length && !pending.length) break;
    if (Date.now() > deadline) {
      return {
        released: false,
        prUrl,
        mergedSha: null,
        reason: "host repo checks did not finish within the release window — PR left open",
      };
    }
    await sleep(CHECK_POLL_MS);
  }

  // 3. Merge (squash, never force) and confirm with the repo's own record.
  const merge = await run(
    ["pr", "merge", prUrl, "-R", slug, "--squash"],
    process.cwd(),
    120_000,
  );
  if (!succeeded(merge)) {
    return {
      released: false,
      prUrl,
      mergedSha: null,
      reason: `merge refused by the host repo: ${failureText(merge)}`,
    };
  }
  const view = await run(
    ["pr", "view", prUrl, "-R", slug, "--json", "state,mergeCommit", "--jq", ".state + \" \" + (.mergeCommit.oid // \"\")"],
    process.cwd(),
    60_000,
  );
  const [state, sha] = succeeded(view) ? view.stdout.trim().split(/\s+/) : ["UNKNOWN", ""];
  if (state !== "MERGED") {
    return {
      released: false,
      prUrl,
      mergedSha: null,
      reason: `merge command succeeded but the PR state reads ${state} — not claiming release`,
    };
  }
  return {
    released: true,
    prUrl,
    mergedSha: sha || null,
    reason: "merged to main after grounded QA, passing tests, and green host-repo checks",
  };
}
